#ifndef SIMULATION_PARAMETERS_HPP
#define SIMULATION_PARAMETERS_HPP

#define WINDOW_SIZE_X 800
#define WINDOW_SIZE_Y 800

#define CELL_COUNT 10
#define GRID_SIZE_X 10
#define GRID_SIZE_Y 10
#define MAX_GEN 10000
#define STEP_PER_GEN 10
#define FPS 10
#define RENDER true

#endif
